### ISSUE TITLE
webkitstatus generation problem

### ISSUE THREAD

**Issue by xfq** [w3c/media-web-roadmap#21]
[data/mediaqueries4.json](https://github.com/w3c/media-web-roadmap/blob/9fa001fb9cbd632f3a2f52d39ffeaf420dfa9847/data/mediaqueries4.json) causes the following error:

```
Traceback (most recent call last):
  File "tools/extract-impl-data.py", line 132, in <module>
    processData()
  File "tools/extract-impl-data.py", line 109, in processData
    data[id] = feature_status(data[id], key, feature_data["impl"][key])
  File "tools/extract-impl-data.py", line 79, in feature_status
    webkitstatus = feature_data["status"].get("status", "")
KeyError: 'status'
```

/cc @dontcallmedom

**Comment by xfq** [comment]
Closing. Thanks!
